/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techsolution;

/**
 *
 * @author j_ohn
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBut2Inven = new javax.swing.JButton();
        jBut2Prove = new javax.swing.JButton();
        jBut2Usua = new javax.swing.JButton();
        jBut2Repor = new javax.swing.JButton();
        jBut2Config = new javax.swing.JButton();
        jButInven = new javax.swing.JButton();
        jButProve = new javax.swing.JButton();
        jButUsuar = new javax.swing.JButton();
        jButRepor = new javax.swing.JButton();
        jButConfi = new javax.swing.JButton();
        JbutSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 140, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Salir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, 130, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Version 1.0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 130, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Proveedores");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 190, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuarios");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 140, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Inventario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 160, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Reportes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 150, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Configuración");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 210, 30));

        jBut2Inven.setFont(new java.awt.Font("MOON GET!", 0, 14)); // NOI18N
        jBut2Inven.setText("Inventario");
        jBut2Inven.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jBut2Inven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2InvenActionPerformed(evt);
            }
        });
        getContentPane().add(jBut2Inven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 40));

        jBut2Prove.setFont(new java.awt.Font("MOON GET!", 0, 14)); // NOI18N
        jBut2Prove.setText("Proveedores");
        jBut2Prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2ProveActionPerformed(evt);
            }
        });
        getContentPane().add(jBut2Prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 40));

        jBut2Usua.setFont(new java.awt.Font("MOON GET!", 0, 14)); // NOI18N
        jBut2Usua.setText("Usuarios");
        jBut2Usua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2UsuaActionPerformed(evt);
            }
        });
        getContentPane().add(jBut2Usua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 40));

        jBut2Repor.setFont(new java.awt.Font("MOON GET!", 0, 14)); // NOI18N
        jBut2Repor.setText("Reportes");
        jBut2Repor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2ReporActionPerformed(evt);
            }
        });
        getContentPane().add(jBut2Repor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 140, 40));

        jBut2Config.setFont(new java.awt.Font("MOON GET!", 0, 12)); // NOI18N
        jBut2Config.setText("Configuracion");
        jBut2Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2ConfigActionPerformed(evt);
            }
        });
        getContentPane().add(jBut2Config, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 140, 40));

        jButInven.setBackground(new java.awt.Color(255, 255, 255));
        jButInven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/317711-128.png"))); // NOI18N
        jButInven.setBorder(null);
        jButInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButInvenActionPerformed(evt);
            }
        });
        getContentPane().add(jButInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 180, 120));

        jButProve.setBackground(new java.awt.Color(255, 255, 255));
        jButProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/379425-128.png"))); // NOI18N
        jButProve.setBorder(null);
        jButProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButProveActionPerformed(evt);
            }
        });
        getContentPane().add(jButProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, 110));

        jButUsuar.setBackground(new java.awt.Color(255, 255, 255));
        jButUsuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/172474-128.png"))); // NOI18N
        jButUsuar.setBorder(null);
        jButUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButUsuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButUsuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 270, -1, -1));

        jButRepor.setBackground(new java.awt.Color(255, 255, 255));
        jButRepor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/216307-128.png"))); // NOI18N
        jButRepor.setBorder(null);
        jButRepor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButReporActionPerformed(evt);
            }
        });
        getContentPane().add(jButRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        jButConfi.setBackground(new java.awt.Color(255, 255, 255));
        jButConfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/171472-128.png"))); // NOI18N
        jButConfi.setBorder(null);
        jButConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButConfiActionPerformed(evt);
            }
        });
        getContentPane().add(jButConfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 150, 130));

        JbutSalir.setBackground(new java.awt.Color(255, 255, 255));
        JbutSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1055069-128.png"))); // NOI18N
        JbutSalir.setBorder(null);
        JbutSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutSalirActionPerformed(evt);
            }
        });
        getContentPane().add(JbutSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HOME.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbutSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutSalirActionPerformed
        dispose();
    }//GEN-LAST:event_JbutSalirActionPerformed

    private void jButConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButConfiActionPerformed
        new Configuracion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButConfiActionPerformed

    private void jButReporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButReporActionPerformed
        new Reportes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButReporActionPerformed

    private void jButUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButUsuarActionPerformed
        new Usuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButUsuarActionPerformed

    private void jButProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButProveActionPerformed
        new Proveedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButProveActionPerformed

    private void jButInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButInvenActionPerformed
        new Inventario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButInvenActionPerformed

    private void jBut2InvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2InvenActionPerformed
        new Inventario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBut2InvenActionPerformed

    private void jBut2ProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2ProveActionPerformed
        new Proveedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBut2ProveActionPerformed

    private void jBut2UsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2UsuaActionPerformed
        new Usuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBut2UsuaActionPerformed

    private void jBut2ReporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2ReporActionPerformed
        new Reportes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBut2ReporActionPerformed

    private void jBut2ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2ConfigActionPerformed
        new Configuracion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBut2ConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbutSalir;
    private javax.swing.JButton jBut2Config;
    private javax.swing.JButton jBut2Inven;
    private javax.swing.JButton jBut2Prove;
    private javax.swing.JButton jBut2Repor;
    private javax.swing.JButton jBut2Usua;
    private javax.swing.JButton jButConfi;
    private javax.swing.JButton jButInven;
    private javax.swing.JButton jButProve;
    private javax.swing.JButton jButRepor;
    private javax.swing.JButton jButUsuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
