/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techsolution;

import Clases.Producto;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ricalv
 */
public class Inventario extends javax.swing.JFrame {

    int codigo;
    String nombre = "";
    String descripcion = "";
    String categoria = "";
    int cantidad = 0;
    double precioc = 0.0;
    double preciov = 0.0;
    int proveedor = 0;
    String ruta = "";
    URL url= null;
    ImageIcon icon = null;
    Producto p = new Producto();
    
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButInven = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtDescripcion = new javax.swing.JTextField();
        jtxtCantidad = new javax.swing.JTextField();
        jtxtPrecioC = new javax.swing.JTextField();
        jtxtPrecioV = new javax.swing.JTextField();
        jtxtProveedor = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jbutGuardar = new javax.swing.JButton();
        txtNombreArchivo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabImagen = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jbutBuscar = new javax.swing.JButton();
        jbutBorrar = new javax.swing.JButton();
        jtxtCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1055069-128.png"))); // NOI18N
        jButSalir.setBorder(null);
        jButSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Salir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 70, 30));

        jButInven.setBackground(new java.awt.Color(255, 255, 255));
        jButInven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/317711-128.png"))); // NOI18N
        jButInven.setBorder(null);
        jButInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButInvenActionPerformed(evt);
            }
        });
        getContentPane().add(jButInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 120));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Proveedor: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Inventario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descripción: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Codigo: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Categoría: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cantidad: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Precio Compra: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, 20));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Precio Venta: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jtxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoActionPerformed(evt);
            }
        });
        jtxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 169, 130, 30));
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 130, 40));
        getContentPane().add(jtxtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 130, 50));
        getContentPane().add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 130, 30));
        getContentPane().add(jtxtPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 130, -1));
        getContentPane().add(jtxtPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 130, -1));
        getContentPane().add(jtxtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 130, -1));

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Guardar imagen");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 110, 20));

        jbutGuardar.setText("Guardar producto");
        jbutGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));
        getContentPane().add(txtNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 190, 80));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre del archivo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 190, -1));

        jLabImagen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabImagen.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 90, 60));

        lblImagen.setForeground(new java.awt.Color(0, 0, 0));
        lblImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 270, 190));

        jbutBuscar.setText("Buscar");
        jbutBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        jbutBorrar.setText("Borrar");
        jbutBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, -1, -1));
        getContentPane().add(jtxtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OTHER.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButSalirActionPerformed

    private void jButInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButInvenActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButInvenActionPerformed

    private void jtxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoActionPerformed

    private void jbutGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutGuardarActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo", "txt");
        archivo.setFileFilter(filtro);
        int opcion = archivo.showSaveDialog(this);
        if(opcion == JFileChooser.APPROVE_OPTION){
        try{BufferedWriter bw = new BufferedWriter(
                        new FileWriter(
                                archivo.getSelectedFile()
                                        .getAbsolutePath()));
        bw.write(jtxtCodigo.getText()+ "  ");
        bw.write(jtxtNombre.getText() + "  ");
        bw.write(jtxtDescripcion.getText() + "  ");
        bw.write(jtxtCategoria.getText() + "  ");
        bw.write(jtxtCantidad.getText() + "  " + "$");
        bw.write(jtxtPrecioC.getText()+ "  " + "$");
        bw.write(jtxtPrecioV.getText() + "  ");
        bw.write(jtxtProveedor.getText() + "  ");
         bw.write(txtNombreArchivo.getText() + "  ");
                bw.close();
        }catch(IOException e)
             {
            e.printStackTrace();
             }
        }
        
        mostrarImagen("/imagenes/8.png");
    }//GEN-LAST:event_jbutGuardarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
         JFileChooser archivo = new JFileChooser();
       int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION){
         File file = archivo.getSelectedFile();
            int altcActual;
            int anchoActual;
           this.txtNombreArchivo.setText(String.valueOf(file));
           Image logo =getToolkit().getImage(this.txtNombreArchivo.getText());
           
           logo=logo.getScaledInstance(250,Math.round(255*(250/logo.getWidth(null))), Image.SCALE_DEFAULT);
           this.lblImagen.setIcon(new ImageIcon(logo));
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void jbutBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBorrarActionPerformed
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jtxtDescripcion.setText("");
        jtxtCategoria.setText("");
        jtxtCantidad.setText("");
        jtxtPrecioC.setText("");
        jtxtPrecioV.setText("");
        jtxtProveedor.setText("");
        txtNombreArchivo.setText("");
        lblImagen.setIcon(null);
    }//GEN-LAST:event_jbutBorrarActionPerformed

    private void jtxtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (p.buscarProducto(jtxtCodigo.getText()) == 1) {

                jtxtNombre.setText(p.getNombre());
                jtxtDescripcion.setText(p.getDescripcion());
                jtxtCategoria.setText(p.getCategoria());
                jtxtCantidad.setText(Integer.toString(p.getCantidad()));
                jtxtPrecioC.setText(Double.toString(p.getPrecioC()));
                jtxtPrecioV.setText(Double.toString(p.getPrecioV()));
                jtxtProveedor.setText(Integer.toString(p.getProveedor()));

                int op = Integer.parseInt(jtxtCodigo.getText());

        switch (op) {
            case 1: 
                this.mostrarImagen("/Imagenes/1.jpg");
                txtNombreArchivo.setText("1.jpg");
                break;
            case 2: 
                this.mostrarImagen("/Imagenes/logo4.png");
                txtNombreArchivo.setText("logo4.png");
                break;
        } 
                        
                
            } else {
                JOptionPane.showMessageDialog(null, "Producto No Encontrado", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jtxtCodigoKeyPressed

    private void jbutBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBuscarActionPerformed
        if (p.buscarProducto(jtxtCodigo.getText()) == 1) {

            jtxtNombre.setText(p.getNombre());
            jtxtDescripcion.setText(p.getDescripcion());
            jtxtCategoria.setText(p.getCategoria());
            jtxtCantidad.setText(Integer.toString(p.getCantidad()));
            jtxtPrecioC.setText(Double.toString(p.getPrecioC()));
            jtxtPrecioV.setText(Double.toString(p.getPrecioV()));
            jtxtProveedor.setText(Integer.toString(p.getProveedor()));

                  int op = Integer.parseInt(jtxtCodigo.getText());

        switch (op) {
            case 1: 
                this.mostrarImagen("/Imagenes/1.jpg");
                txtNombreArchivo.setText("1.jpg");
                break;
            case 2: 
                this.mostrarImagen("/Imagenes/logo4.png");
                txtNombreArchivo.setText("logo4.png");
                break;
        }
      

        } else {
            JOptionPane.showMessageDialog(null, "Producto No Encontrado", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbutBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }
    public void mostrarImagen(String urlImagen){
    url = this.getClass().getResource(urlImagen);
    icon = new ImageIcon(url);
     jLabImagen.setIcon(icon);
     // jLabImagen.setText("Opción : "+ opcion + "Texto : "+ cadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton jButInven;
    private javax.swing.JButton jButSalir;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbutBorrar;
    private javax.swing.JButton jbutBuscar;
    private javax.swing.JButton jbutGuardar;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtCategoria;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPrecioC;
    private javax.swing.JTextField jtxtPrecioV;
    private javax.swing.JTextField jtxtProveedor;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtNombreArchivo;
    // End of variables declaration//GEN-END:variables
}
