/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techsolution;

import Clases.Producto;
import Conexion.Conexion;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ricalv
 */
public class Venta extends javax.swing.JFrame {

    int codigo;
    int num_venta;
    String nombre = "";
    String descripcion = "";
    double cantidad = 0.0;
    double preciov = 0.0;
    double total = 0.0;
    String ruta = "";
    URL url= null;
    ImageIcon icon = null;
    Producto p = new Producto();
    
    public Venta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    public JTextField getJtxtCantidad() {
        return jtxtCantidad;
    }


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtDescripcion = new javax.swing.JTextField();
        jtxtCantidad = new javax.swing.JTextField();
        jtxtPrecioV = new javax.swing.JTextField();
        jLabImagen = new javax.swing.JLabel();
        jbutBuscar = new javax.swing.JButton();
        jbutBorrar = new javax.swing.JButton();
        jbutComprar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtCalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtGuardarVenta = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1055069-128.png"))); // NOI18N
        jButSalir.setBorder(null);
        jButSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 90, 100));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("MOON GET!", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Salir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 70, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("MOON GET!", 0, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Venta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 210, 90));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descripción: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cantidad: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Precio Total: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jtxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoActionPerformed(evt);
            }
        });
        jtxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 30));

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 130, 40));
        getContentPane().add(jtxtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 130, 50));

        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 130, 30));

        jtxtPrecioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioVActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 30));

        jLabImagen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabImagen.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 70, 50));

        jbutBuscar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbutBuscar.setText("Buscar");
        jbutBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 100, 50));

        jbutBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbutBorrar.setText("Borrar");
        jbutBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 50));

        jbutComprar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbutComprar.setText("Comprar");
        jbutComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 200, 70));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Precio Venta: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 130, 30));

        jtxtCalcular.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtxtCalcular.setText("Calcular");
        jtxtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 110, 50));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Codigo: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jtxtGuardarVenta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtGuardarVenta.setText("Click para confirmar");
        jtxtGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGuardarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtGuardarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OTHER.png"))); // NOI18N
        jLabel1.setText("P");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -50, 1040, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButSalirActionPerformed

    private void jtxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoActionPerformed

    private void jtxtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (p.buscarProducto(jtxtCodigo.getText()) == 1) {

                
                jtxtNombre.setText(p.getNombre());
                jtxtDescripcion.setText(p.getDescripcion());
                jtxtPrecioV.setText(Double.toString(p.getPrecioV()));

              
                        
                
            } else {
                JOptionPane.showMessageDialog(null, "Producto No Encontrado", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jtxtCodigoKeyPressed

    private void jbutBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBuscarActionPerformed
        if (p.buscarProducto(jtxtCodigo.getText()) == 1) {

            
            jtxtNombre.setText(p.getNombre());
            jtxtDescripcion.setText(p.getDescripcion());
            jtxtPrecioV.setText(Double.toString(p.getPrecioV()));
            


        } else {
            JOptionPane.showMessageDialog(null, "Producto No Encontrado", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbutBuscarActionPerformed

    private void jbutComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutComprarActionPerformed
        // TODO add yo
        Map parameters = new HashMap();
        parameters.put("Nombre", "Ricardo Alvarado");
        try{
            JasperReport report = JasperCompileManager.compileReport("C:\\Users\\rical\\Documents\\NetBeansProjects\\nuevo\\TechSolution\\TechSolution\\src\\reportes\\Venta.jrxml");
            
            JasperPrint print = JasperFillManager.fillReport(report, parameters, new Conexion().ConectarBD());
            
            JasperExportManager.exportReportToPdfFile(print, "C:\\Users\\rical\\Documents\\NetBeansProjects\\nuevo\\TechSolution\\TechSolution\\src\\reportes\\Venta.pdf");
            
            JasperViewer.viewReport(print, false);
        }
        catch (JRException e){
            System.out.println("Error al generar el reporte "+ e);
        }
    
    }//GEN-LAST:event_jbutComprarActionPerformed

    private void jtxtPrecioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioVActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtPrecioVActionPerformed

    private void jbutBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBorrarActionPerformed
        
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jtxtDescripcion.setText("");
        jtxtCantidad.setText("");
        jtxtPrecioV.setText("");
        jtxtTotal.setText("");
    }//GEN-LAST:event_jbutBorrarActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCalcularActionPerformed
        // TODO add your handling code here:
        total=Double.parseDouble(jtxtCantidad.getText())*Double.parseDouble(jtxtPrecioV.getText());
        jtxtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_jtxtCalcularActionPerformed

    private void jtxtGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGuardarVentaActionPerformed
        // TODO add your handling code here:
        p.setCodigov(Integer.parseInt(jtxtCodigo.getText()));
        p.setNombrev(jtxtNombre.getText());
        p.setDescripcionv(jtxtDescripcion.getText());
        p.setCantidadv(Integer.parseInt( jtxtCantidad.getText()));
        p.setPrecioVv(Double.parseDouble(jtxtPrecioV.getText()));
        p.setTotal(Double.parseDouble(jtxtTotal.getText()));
        if(p.guardarproductoVenta() == 1){
            JOptionPane.showMessageDialog(null, 
                                    "Producto Almacenado en Venta",
                                    "mensaje",
                                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jtxtGuardarVentaActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }
    public void mostrarImagen(String urlImagen){
    url = this.getClass().getResource(urlImagen);
    icon = new ImageIcon(url);
    
     //lblImagen.setIcon(icon);
     // jLabImagen.setText("Opción : "+ opcion + "Texto : "+ cadena);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButSalir;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbutBorrar;
    private javax.swing.JButton jbutBuscar;
    private javax.swing.JButton jbutComprar;
    private javax.swing.JButton jtxtCalcular;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JToggleButton jtxtGuardarVenta;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPrecioV;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
